// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protos.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace vivego.Proto.PubSub.Messages {

  /// <summary>Holder for reflection information generated from Protos.proto</summary>
  public static partial class ProtosReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxQcm90b3MucHJvdG8SE3ZpdmVnby5Qcm90by5QdWJTdWIaFlJlZmVyZW5j",
            "ZS9Qcm90b3MucHJvdG8aKnZpdmVnby5QdWJsaXNoU3Vic2NyaWJlL1Byb3Rv",
            "L1Byb3Rvcy5wcm90byJlChFQcm90b1N1YnNjcmlwdGlvbhI3CgxTdWJzY3Jp",
            "cHRpb24YASABKAsyIS52aXZlZ28uUHJvdG8uUHViU3ViLlN1YnNjcmlwdGlv",
            "bhIXCgNQSUQYAiABKAsyCi5hY3Rvci5QSURCH6oCHHZpdmVnby5Qcm90by5Q",
            "dWJTdWIuTWVzc2FnZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.ProtosReflection.Descriptor, global::vivego.PublishSubscribe.ProtosReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::vivego.Proto.PubSub.Messages.ProtoSubscription), global::vivego.Proto.PubSub.Messages.ProtoSubscription.Parser, new[]{ "Subscription", "PID" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtoSubscription : pb::IMessage<ProtoSubscription> {
    private static readonly pb::MessageParser<ProtoSubscription> _parser = new pb::MessageParser<ProtoSubscription>(() => new ProtoSubscription());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProtoSubscription> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::vivego.Proto.PubSub.Messages.ProtosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoSubscription() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoSubscription(ProtoSubscription other) : this() {
      Subscription = other.subscription_ != null ? other.Subscription.Clone() : null;
      PID = other.pID_ != null ? other.PID.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoSubscription Clone() {
      return new ProtoSubscription(this);
    }

    /// <summary>Field number for the "Subscription" field.</summary>
    public const int SubscriptionFieldNumber = 1;
    private global::vivego.PublishSubscribe.Subscription subscription_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::vivego.PublishSubscribe.Subscription Subscription {
      get { return subscription_; }
      set {
        subscription_ = value;
      }
    }

    /// <summary>Field number for the "PID" field.</summary>
    public const int PIDFieldNumber = 2;
    private global::Proto.PID pID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.PID PID {
      get { return pID_; }
      set {
        pID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProtoSubscription);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProtoSubscription other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Subscription, other.Subscription)) return false;
      if (!object.Equals(PID, other.PID)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (subscription_ != null) hash ^= Subscription.GetHashCode();
      if (pID_ != null) hash ^= PID.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (subscription_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Subscription);
      }
      if (pID_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (subscription_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Subscription);
      }
      if (pID_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProtoSubscription other) {
      if (other == null) {
        return;
      }
      if (other.subscription_ != null) {
        if (subscription_ == null) {
          subscription_ = new global::vivego.PublishSubscribe.Subscription();
        }
        Subscription.MergeFrom(other.Subscription);
      }
      if (other.pID_ != null) {
        if (pID_ == null) {
          pID_ = new global::Proto.PID();
        }
        PID.MergeFrom(other.PID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (subscription_ == null) {
              subscription_ = new global::vivego.PublishSubscribe.Subscription();
            }
            input.ReadMessage(subscription_);
            break;
          }
          case 18: {
            if (pID_ == null) {
              pID_ = new global::Proto.PID();
            }
            input.ReadMessage(pID_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
